on:
  push:
    branches:
      - main
jobs:
  build-and-publish-latest:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2 # Checking out the repo

          - name: Build and Publish latest Docker image
            uses: VaultVulp/gp-docker-action@1.6.0
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                image-name: restricted-personal-pages
